export interface Division {
  divisionId: string;
  name: string;
  description?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Stipulation {
  stipulationId: string;
  name: string;
  description?: string;
  createdAt: string;
  updatedAt: string;
}

export interface MatchType {
  matchTypeId: string;
  name: string;
  description?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Video {
  videoId: string;
  title: string;
  description: string;
  videoUrl: string;
  thumbnailUrl: string;
  category: 'match' | 'highlight' | 'promo' | 'other';
  tags: string[];
  isPublished: string; // 'true' | 'false' — string for DynamoDB GSI
  uploadedBy: string;
  createdAt: string;
  updatedAt: string;
}

export interface Announcement {
  announcementId: string;
  title: string;
  body: string;
  priority: number;
  isActive: string; // 'true' | 'false' — string for DynamoDB GSI
  expiresAt?: string;
  videoUrl?: string;
  createdBy: string;
  createdAt: string;
  updatedAt: string;
}

export interface Company {
  companyId: string;
  name: string;
  abbreviation?: string;
  imageUrl?: string;
  description?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Show {
  showId: string;
  name: string;
  companyId: string;
  description?: string;
  schedule?: string;
  dayOfWeek?: string;
  imageUrl?: string;
  createdAt: string;
  updatedAt: string;
}

export interface AppNotification {
  userId: string;
  createdAt: string;
  notificationId: string;
  type: string;
  title: string;
  message: string;
  isRead: boolean;
  linkUrl?: string;
  linkText?: string;
  metadata?: Record<string, unknown>;
  updatedAt: string;
}

export interface WrestlerOverall {
  playerId: string;
  mainOverall: number;
  alternateOverall?: number;
  submittedAt: string;
  updatedAt: string;
}

export interface Season {
  seasonId: string;
  name: string;
  startDate: string;
  endDate?: string;
  status: 'active' | 'completed';
  createdAt: string;
  updatedAt: string;
}

export interface SeasonAward {
  awardId: string;
  seasonId: string;
  name: string;
  awardType: string;
  playerId: string;
  playerName: string;
  description?: string | null;
  value?: string;
  autoGenerated?: boolean;
  createdAt?: string;
}

// ─── Wave 4 types ──────────────────────────────────────────────────

export interface Player {
  playerId: string;
  userId?: string;
  name: string;
  currentWrestler: string;
  alternateWrestler?: string;
  wins: number;
  losses: number;
  draws: number;
  imageUrl?: string;
  psnId?: string;
  divisionId?: string;
  companyId?: string;
  stableId?: string;
  tagTeamId?: string;
  alignment?: 'face' | 'heel' | 'neutral';
  mainOverall?: number;
  createdAt: string;
  updatedAt: string;
}

export type ChallengeStatus = 'pending' | 'accepted' | 'declined' | 'countered' | 'scheduled' | 'expired' | 'cancelled';

export interface Challenge {
  challengeId: string;
  challengerId: string;
  challengedId: string;
  matchType: string;
  stipulation?: string;
  championshipId?: string;
  message?: string;
  status: ChallengeStatus;
  responseMessage?: string;
  counteredChallengeId?: string;
  matchId?: string;
  challengeMode?: 'singles' | 'tag_team';
  challengerTagTeamId?: string;
  challengedTagTeamId?: string;
  expiresAt: string;
  createdAt: string;
  updatedAt: string;
}

export type TagTeamStatus = 'pending_partner' | 'pending_admin' | 'active' | 'dissolved';

export interface TagTeam {
  tagTeamId: string;
  name: string;
  player1Id: string;
  player2Id: string;
  imageUrl?: string;
  status: TagTeamStatus;
  wins: number;
  losses: number;
  draws: number;
  createdAt: string;
  updatedAt: string;
  dissolvedAt?: string;
}

export type StableStatus = 'pending' | 'approved' | 'active' | 'disbanded';

export interface Stable {
  stableId: string;
  name: string;
  leaderId: string;
  memberIds: string[];
  imageUrl?: string;
  status: StableStatus;
  wins: number;
  losses: number;
  draws: number;
  createdAt: string;
  updatedAt: string;
  disbandedAt?: string;
}

export type StableInvitationStatus = 'pending' | 'accepted' | 'declined' | 'expired';

export interface StableInvitation {
  invitationId: string;
  stableId: string;
  invitedPlayerId: string;
  invitedByPlayerId: string;
  status: StableInvitationStatus;
  message?: string;
  expiresAt: string;
  createdAt: string;
  updatedAt: string;
}

export type TransferRequestStatus = 'pending' | 'approved' | 'rejected';

export interface TransferRequest {
  requestId: string;
  playerId: string;
  fromDivisionId: string;
  toDivisionId: string;
  reason: string;
  status: TransferRequestStatus;
  createdAt: string;
  updatedAt: string;
  reviewedBy?: string;
  reviewNote?: string;
}

export type StorylineRequestType = 'storyline' | 'backstage_attack' | 'rivalry';
export type StorylineRequestStatus = 'pending' | 'acknowledged' | 'declined';

export interface StorylineRequest {
  requestId: string;
  requesterId: string;
  targetPlayerIds: string[];
  requestType: StorylineRequestType;
  description: string;
  status: StorylineRequestStatus;
  gmNote?: string;
  reviewedBy?: string;
  createdAt: string;
  updatedAt: string;
}

export type EventType = 'ppv' | 'weekly' | 'special' | 'house';
export type EventStatus = 'upcoming' | 'in-progress' | 'completed' | 'cancelled';
export type MatchDesignation = 'pre-show' | 'opener' | 'midcard' | 'co-main' | 'main-event';

export interface MatchCardEntry {
  position: number;
  matchId: string;
  designation: MatchDesignation;
  notes?: string;
}

export interface LeagueEvent {
  eventId: string;
  name: string;
  eventType: EventType;
  date: string;
  venue?: string;
  description?: string;
  imageUrl?: string;
  themeColor?: string;
  status: EventStatus;
  seasonId?: string;
  companyIds?: string[];
  showId?: string;
  matchCards: MatchCardEntry[];
  attendance?: number;
  rating?: number;
  fantasyEnabled?: boolean;
  fantasyLocked?: boolean;
  fantasyBudget?: number;
  fantasyPicksPerDivision?: number;
  createdAt: string;
  updatedAt: string;
}

export type EventCheckInStatus = 'available' | 'tentative' | 'unavailable';

export interface EventCheckIn {
  eventId: string;
  playerId: string;
  status: EventCheckInStatus;
  checkedInAt: string;
  ttl?: number;
}

export type PromoType = 'open-mic' | 'call-out' | 'response' | 'pre-match' | 'post-match' | 'championship' | 'return';
export type ReactionType = 'fire' | 'mic' | 'trash' | 'mind-blown' | 'clap';

export interface Promo {
  promoId: string;
  playerId: string;
  promoType: PromoType;
  title?: string;
  content: string;
  targetPlayerId?: string;
  targetPromoId?: string;
  matchId?: string;
  championshipId?: string;
  imageUrl?: string;
  challengeMode?: 'singles' | 'tag_team';
  challengerTagTeamName?: string;
  targetTagTeamName?: string;
  reactions: Record<string, ReactionType>;
  reactionCounts: Record<ReactionType, number>;
  isPinned: boolean;
  isHidden: boolean;
  createdAt: string;
  updatedAt: string;
}

// ─── Wave 5 types ──────────────────────────────────────────────────

export interface Match {
  matchId: string;
  date: string;
  matchFormat?: string;
  matchType?: string; // legacy field name
  stipulationId?: string;
  participants: string[];
  teams?: string[][];
  winners?: string[];
  losers?: string[];
  isDraw?: boolean;
  isChampionship?: boolean;
  championshipId?: string;
  tournamentId?: string;
  seasonId?: string;
  eventId?: string;
  status: 'scheduled' | 'completed' | 'cancelled';
  starRating?: number;
  matchOfTheNight?: boolean;
  createdAt: string;
  updatedAt?: string;
}

export interface Championship {
  championshipId: string;
  name: string;
  type: 'singles' | 'tag';
  currentChampion?: string | string[];
  imageUrl?: string;
  isActive?: boolean;
  defenses?: number;
  createdAt: string;
  updatedAt: string;
}

export interface ChampionshipHistoryEntry {
  championshipId: string;
  wonDate: string;
  champion: string | string[];
  lostDate?: string;
  daysHeld?: number;
  defenses?: number;
  matchId?: string;
  updatedAt?: string;
}

export interface Tournament {
  tournamentId: string;
  name: string;
  type: 'single-elimination' | 'round-robin';
  status: string;
  participants?: string[];
  brackets?: unknown;
  standings?: unknown;
  winner?: string;
  createdAt: string;
  updatedAt?: string;
}

export interface SeasonStanding {
  seasonId: string;
  playerId: string;
  wins: number;
  losses: number;
  draws: number;
  updatedAt: string;
}
