export interface Division {
  divisionId: string;
  name: string;
  description?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Stipulation {
  stipulationId: string;
  name: string;
  description?: string;
  createdAt: string;
  updatedAt: string;
}

export interface MatchType {
  matchTypeId: string;
  name: string;
  description?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Video {
  videoId: string;
  title: string;
  description: string;
  videoUrl: string;
  thumbnailUrl: string;
  category: 'match' | 'highlight' | 'promo' | 'other';
  tags: string[];
  isPublished: string; // 'true' | 'false' — string for DynamoDB GSI
  uploadedBy: string;
  createdAt: string;
  updatedAt: string;
}

export interface Announcement {
  announcementId: string;
  title: string;
  body: string;
  priority: number;
  isActive: string; // 'true' | 'false' — string for DynamoDB GSI
  expiresAt?: string;
  videoUrl?: string;
  createdBy: string;
  createdAt: string;
  updatedAt: string;
}

export interface Company {
  companyId: string;
  name: string;
  abbreviation?: string;
  imageUrl?: string;
  description?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Show {
  showId: string;
  name: string;
  companyId: string;
  description?: string;
  schedule?: string;
  dayOfWeek?: string;
  imageUrl?: string;
  createdAt: string;
  updatedAt: string;
}

export interface AppNotification {
  userId: string;
  createdAt: string;
  notificationId: string;
  type: string;
  title: string;
  message: string;
  isRead: boolean;
  linkUrl?: string;
  linkText?: string;
  metadata?: Record<string, unknown>;
  updatedAt: string;
}

export interface WrestlerOverall {
  playerId: string;
  mainOverall: number;
  alternateOverall?: number;
  submittedAt: string;
  updatedAt: string;
}

export interface Season {
  seasonId: string;
  name: string;
  startDate: string;
  endDate?: string;
  status: 'active' | 'completed';
  createdAt: string;
  updatedAt: string;
}

export interface SeasonAward {
  awardId: string;
  seasonId: string;
  name: string;
  awardType: string;
  playerId: string;
  playerName: string;
  description?: string | null;
  value?: string;
  autoGenerated?: boolean;
  createdAt?: string;
}
