import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen, waitFor, fireEvent } from '@testing-library/react';
import { BrowserRouter } from 'react-router-dom';

// --- Hoisted mocks ---
const {
  mockGetAllSeasons,
  mockGetAllPlayers,
  mockGetAwards,
  mockCreateAward,
  mockDeleteAward,
} = vi.hoisted(() => ({
  mockGetAllSeasons: vi.fn(),
  mockGetAllPlayers: vi.fn(),
  mockGetAwards: vi.fn(),
  mockCreateAward: vi.fn(),
  mockDeleteAward: vi.fn(),
}));

vi.mock('../../../services/api', () => ({
  seasonsApi: { getAll: mockGetAllSeasons },
  playersApi: { getAll: mockGetAllPlayers },
  seasonAwardsApi: {
    getAll: mockGetAwards,
    create: mockCreateAward,
    delete: mockDeleteAward,
  },
}));

vi.mock('react-i18next', () => ({
  useTranslation: () => ({
    t: (key: string, opts?: Record<string, string>) => {
      const translations: Record<string, string> = {
        'common.loading': 'Loading...',
        'common.cancel': 'Cancel',
        'common.delete': 'Delete',
        'seasonAwards.admin.title': 'Manage Season Awards',
        'seasonAwards.admin.selectSeason': 'Season',
        'seasonAwards.admin.chooseSeason': '-- Select a season --',
        'seasonAwards.admin.createAward': 'Create Award',
        'seasonAwards.admin.awardName': 'Award Name',
        'seasonAwards.admin.awardPlayer': 'Player',
        'seasonAwards.admin.choosePlayer': '-- Select a player --',
        'seasonAwards.admin.description': 'Description',
        'seasonAwards.admin.value': 'Value',
        'seasonAwards.admin.createSuccess': 'Award created successfully!',
        'seasonAwards.admin.deleteSuccess': 'Award deleted successfully!',
        'seasonAwards.admin.confirmDelete': `Are you sure you want to delete the award "${opts?.name}"?`,
        'seasonAwards.autoAwards': 'Auto-Generated Awards',
        'seasonAwards.customAwards': 'Custom Awards',
        'seasonAwards.noAwards': 'No awards for this season yet.',
      };
      return translations[key] || key;
    },
  }),
}));

vi.mock('../ManageSeasonAwards.css', () => ({}));

import ManageSeasonAwards from '../ManageSeasonAwards';

// --- Test data ---
const mockSeasons = [
  { seasonId: 's1', name: 'Season 1', startDate: '2025-01-01', status: 'completed' as const, createdAt: '2025-01-01', updatedAt: '2025-05-31' },
  { seasonId: 's2', name: 'Season 2', startDate: '2025-06-01', status: 'active' as const, createdAt: '2025-06-01', updatedAt: '2025-06-01' },
];

const mockPlayers = [
  { playerId: 'p1', name: 'Player One', currentWrestler: 'W1', wins: 5, losses: 2, draws: 0, createdAt: '2025-01-01', updatedAt: '2025-01-01' },
  { playerId: 'p2', name: 'Player Two', currentWrestler: 'W2', wins: 3, losses: 4, draws: 0, createdAt: '2025-01-01', updatedAt: '2025-01-01' },
];

const mockAwardsResponse = {
  seasonId: 's1',
  autoAwards: [
    { awardId: 'auto-mvp', seasonId: 's1', name: 'MVP', awardType: 'mvp', playerId: 'p1', playerName: 'Player One', value: '5 wins', autoGenerated: true },
  ],
  customAwards: [
    { awardId: 'c1', seasonId: 's1', name: 'Best Promo', awardType: 'custom', playerId: 'p2', playerName: 'Player Two', description: 'Great mic work', autoGenerated: false, createdAt: '2025-05-01' },
  ],
};

function renderComponent() {
  return render(
    <BrowserRouter>
      <ManageSeasonAwards />
    </BrowserRouter>
  );
}

describe('ManageSeasonAwards', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    vi.spyOn(window, 'confirm').mockReturnValue(true);
  });

  it('renders season list and awards after loading', async () => {
    mockGetAllSeasons.mockResolvedValue(mockSeasons);
    mockGetAllPlayers.mockResolvedValue(mockPlayers);
    mockGetAwards.mockResolvedValue(mockAwardsResponse);

    renderComponent();

    await waitFor(() => {
      expect(screen.getByText('Manage Season Awards')).toBeInTheDocument();
    });

    // Season selector
    expect(screen.getByLabelText('Season')).toBeInTheDocument();

    // Auto awards section
    await waitFor(() => {
      expect(screen.getByText('Auto-Generated Awards')).toBeInTheDocument();
    });
    expect(screen.getByText('MVP')).toBeInTheDocument();

    // Custom awards section
    expect(screen.getByText('Custom Awards')).toBeInTheDocument();
    expect(screen.getByText('Best Promo')).toBeInTheDocument();
  });

  it('creates a custom award via the form', async () => {
    mockGetAllSeasons.mockResolvedValue(mockSeasons);
    mockGetAllPlayers.mockResolvedValue(mockPlayers);
    mockGetAwards.mockResolvedValue({ seasonId: 's1', autoAwards: [], customAwards: [] });
    mockCreateAward.mockResolvedValue({
      awardId: 'new-1',
      seasonId: 's1',
      name: 'Rookie Award',
      awardType: 'custom',
      playerId: 'p1',
      playerName: 'Player One',
    });

    renderComponent();

    await waitFor(() => {
      expect(screen.getByText('Manage Season Awards')).toBeInTheDocument();
    });

    // Wait for awards to load, then click Create Award
    await waitFor(() => {
      expect(screen.getByText('No awards for this season yet.')).toBeInTheDocument();
    });

    const createButtons = screen.getAllByText('Create Award');
    fireEvent.click(createButtons[0]);

    // Fill form
    fireEvent.change(screen.getByLabelText('Award Name'), { target: { value: 'Rookie Award' } });
    fireEvent.change(screen.getByLabelText('Player'), { target: { value: 'p1' } });

    // Submit
    const submitButtons = screen.getAllByText('Create Award');
    fireEvent.click(submitButtons[submitButtons.length - 1]);

    await waitFor(() => {
      expect(mockCreateAward).toHaveBeenCalledWith('s1', {
        name: 'Rookie Award',
        playerId: 'p1',
        description: undefined,
      });
    });
  });

  it('deletes a custom award with confirmation', async () => {
    mockGetAllSeasons.mockResolvedValue(mockSeasons);
    mockGetAllPlayers.mockResolvedValue(mockPlayers);
    mockGetAwards.mockResolvedValue(mockAwardsResponse);
    mockDeleteAward.mockResolvedValue(undefined);

    renderComponent();

    await waitFor(() => {
      expect(screen.getByText('Custom Awards')).toBeInTheDocument();
    });

    const deleteButtons = screen.getAllByRole('button', { name: 'Delete' });
    fireEvent.click(deleteButtons[0]);

    expect(window.confirm).toHaveBeenCalledWith(
      expect.stringContaining('Best Promo')
    );

    await waitFor(() => {
      expect(mockDeleteAward).toHaveBeenCalledWith('s1', 'c1');
    });
  });
});
