#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const docsDir = path.join(root, 'docs');
const outPath = path.join(root, 'functions', 'docs', 'docsEmbed.generated.ts');

function escapeForTemplateLiteral(s) {
  return s
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${');
}

const yaml = fs.readFileSync(path.join(docsDir, 'openapi.yaml'), 'utf8');
const html = fs.readFileSync(path.join(docsDir, 'swagger.html'), 'utf8');

const out = `// Generated by scripts/embed-docs.js - do not edit by hand. Run: node scripts/embed-docs.js

export const OPENAPI_YAML = \`${escapeForTemplateLiteral(yaml)}\`;

export const SWAGGER_HTML = \`${escapeForTemplateLiteral(html)}\`;
`;

fs.writeFileSync(outPath, out, 'utf8');
console.log('Wrote', outPath);
console.log('OPENAPI_YAML length:', yaml.length, 'SWAGGER_HTML length:', html.length);